version: 2
updates:
  # Fetch and update latest `npm` pkgs
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      # * ignore all major updates relating to Nuxt v3 support
      - dependency-name: "nuxt"
#         update-types: ["version-update:semver-major"]
        versions: ["3.x"]
      - dependency-name: "@vue/test-utils"
        update-types: ["version-update:semver-major"]
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
