[build]
  # Directory containing files to be published
  publish = "dist"
  # Default build command.
  command = "npm run generate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = '''
    default-src https: 'self';
    style-src https: 'self' 'unsafe-inline';
    script-src https: 'self' 'unsafe-inline';
    img-src https: *;
    object-src 'none'
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Feature-Policy = '''
    ambient-light-sensor 'none';
    geolocation 'none';
    midi 'none';
    microphone 'none';
    camera 'none';
    magnetometer 'none';
    speaker 'none'
    '''
